### PR TITLE
Added SuccessHttpResponseCode hook setting

### PR DESCRIPTION
**Pull request by aioobe**
Revamp of PR https://github.com/adnanh/webhook/pull/259

Issue 1, 2 and 3 should have been taken care of.

I'm struggling with item 4 though. First time writing go, and I'm a bit lost. I suspect I should modify `webhook_test.go` and do something very similar to

	// test with custom return code
	{"empty payload", "github", nil, `{}`, false, http.StatusBadRequest, `Hook rules were not satisfied.`, ``},
	// test with custom invalid http code, should default to 200 OK
	{"empty payload", "bitbucket", nil, `{}`, false, http.StatusOK, `Hook rules were not satisfied.`, ``},

@adnanh would you mind filling in the blanks here? (I'd be happy to read your patch and learn how to do it myslef for the next patch!) Or alternatively, explaining the details, including how to run tests locally, and I should be able to wrap it up.

### CODE REVIEW

**Comment by aioobe** [comment]
Any chance we could get closure on this? I'm recommend using this tool in https://github.com/aioobe/dead-simple-jekyll-comments but it's annoying to instruct people to patch it / use a fork.

**Comment by adnanh** [comment]
Hey, sorry for the wait, I'll get this in as soon as I can. Life is busy at the moment, but hopefully I'll find a few hours this week to get this done.

**Comment by adnanh** [comment]
Thank you very much :-)

**Comment by aioobe** [comment]
And thank you for creating this awesome little tool. It's used on a daily basis for processing comments over at programming.guide.

**Comment by adnanh** [comment]
Cool :-) I created it to scratch my own itch, but it's evolved quite a bit since then thanks to this wonderful community.

**Pull request merged**
