### PR TITLE
Add sha256 payload check

### PR DESCRIPTION
**Pull request by raphink**
Recent versions of Gogs use sha256 for payload checking:

```json
        {
          "match":
          {
            "type": "payload-hash-sha256",
            "secret": "%{HOOKS_SECRET}",
            "parameter":
            {
              "source": "header",
              "name": "X-Gogs-Signature"
            }
          }
        }
```

### CODE REVIEW

**Comment by mcanevet** [comment]
Works fine with gogs

**Comment by adnanh** [comment]
Thanks for the contribution! This looks awesome, could you just close this PR and open a new one on the development branch :-)

**Comment by raphink** [comment]
I changed the base but now I need to rebase the files.

**Comment by raphink** [comment]
I've rebased so it should be good now.

**Comment by raphink** [comment]
@adnanh this should be to go now.

**Comment by adnanh** [comment]
Done, would you be kind enough to update the wiki pages :-)

**Comment by mcanevet** [comment]
@adnanh done!

**Pull request merged**
