### PR TITLE
Add support for building snaps

### PR DESCRIPTION
**Pull request by igorljubuncic**
Hey Adnan,

I've created this PR to request support for building a snap package of webhook.

I read the guidelines, and I outlined all the technical steps needed to get this done.
I ran the same set of tests you have on the GH page, and I had webhook running correctly.

Basically, this PR shows how to build and run webhook as a snap.

**Overview**

- Snaps are cross-distro Linux software packages, supported on LTS and non-LTS Ubuntus many others distributions (Debian, Fedora, openSUSE, etc).
- Snaps come with automatic updates.
- Snaps are featured in the Snap Store (snapcraft.io/store), with audience of millions.
- Snaps are standalone, isolated apps, so you fully control the release cycle.

**Build and test**

You can use:

- local system with snapcraft command line tool <-- this PR covers this
- build/CI tool/system of your choice
- our online, free build service (build.snapcraft.io)

**Build locally**

Used Ubuntu 18.04 for this.

snap install snapcraft --classic --beta
git clone https://github.com/igorljubuncic/webhook.git
cd webhook
git checkout add-snapcraft
snapcraft

This command will generate a <webhook-version>.snap file, something like webhook_1.0_amd64.snap.

**Install locally**

snap install webhook_1.0_amd64.snap --dangerous

The --dangerous flag is necessary because the app (snap) hasn’t gone through the snap store review process and is not digitally signed.

**Run webhook**

snap run webhook

**Register dev account**

In the snap store at: https://snapcraft.io/account.

**Register webhook name in the store**

This is done on the command line with snapcraft:

snapcraft login
snapcraft register

**Upload/push webhook to the store**

snapcraft push webhook_1.0_amd64.snap --release edge

We use release channels to denote risk, as follows:

- edge, typically for git master
- beta, beta testing
- candidate
- stable

You can promote after testing and validation.

**Install from store for (a second) test**

snap install webhook --edge

I think this covers it.

Once you land the PR, we can help you with the promotion. Feel free to ask any questions you may have.

Thanks!

### CODE REVIEW

**Comment by moorereason** [comment]
Can this live in https://github.com/adnanh/webhook-contrib?

**Comment by igorljubuncic** [comment]
Technically yes, it depends how you call snapcraft - it will expect to find the yaml in the current working directory or a snap sub-directory. Otherwise, you might get an error from snapcraft complaining about not finding the file.

**Comment by adnanh** [comment]
Hey @igorljubuncic , thanks a lot for creating this, I will definitely start publishing to the Snap store!

As @moorereason noted, this file would be better suited for the `webhook-contrib` repository. Would you mind creating a PR over there?

Next webhook release should hopefully be also available at the Snap store, thank you :-)

**Comment by igorljubuncic** [comment]
Thank you, and sure thing, I'll create this in the contrib repo.
Igor

**Comment by adnanh** [comment]
Looks like someone already registered the `webhook` snap name. I contacted the snapcraft, and they're suggesting that I contact the owner directly, so I'll do that :-)

In the meantime, they also require some kind of a proof that I am the author of webhook, so I'll direct them to this comment. 

@Natalia Yes, I contacted you using my e-mail (adnanh@gmail.com) and snap user name adnan.h :-)

**Comment by adnanh** [comment]
It's done! The 2.6.9 is on the snap store, I've updated the README.md accordingly. :-)

**Comment by igorljubuncic** [comment]
Sweet work! Can I also suggest you add a couple of screenshots, too. People love apps with screenshots (and even videos). We've got this page that explains how to maximize exposure and draw users:

https://snapcraft.io/blog/make-your-snap-store-page-pop

We'll also feature webhook in a couple of weeks in our social media.

**Comment by adnanh** [comment]
@igorljubuncic Cool! It's weird taking a screenshot of a CLI tool, but I'll go ahead and make a few, just for the sake of completeness... :-)

**Comment by adnanh** [comment]
@igorljubuncic The snapstore does not allow me to upload the `banner.png` with the specified dimensions (1218x240), I'm getting the following error message:
> The screenshot "banner.png" has an aspect ratio of "203:40". It needs to be at least "1:2" and at most "2:1".

:-(

**Comment by igorljubuncic** [comment]
There are some limitations to what you can upload. I would suggest adding a transparent or white channel for padding, but that could end up not looking pretty. Can you share the banner so I can give you maybe a suggestion on how to tweak it?

**Comment by adnanh** [comment]
Here's the banner that I quickly threw together :joy: 
banner

**Comment by adnanh** [comment]
I was just following the steps outlined in the guide you've posted here, I can create 2:1 ratio banner, that's not a problem for me. Is the guide perhaps outdated?

**Comment by igorljubuncic** [comment]
It is possible. So I'll talk to our design guys too.

**Comment by adnanh** [comment]
Closing this, as it has been merged in the webhook-contrib repo.

**Pull request closed without merging**
