### PR TITLE
Add option to capture output of failed commands

### PR DESCRIPTION
**Pull request by gdubicki**
This implements proposal 1 from https://github.com/adnanh/webhook/issues/87#issuecomment-250903976 .

### CODE REVIEW

**Comment by gdubicki** [comment]
Of course https://github.com/adnanh/webhook/wiki/Hook-Definition would need to be edited too to document the new feature.

**Comment by adnanh** [comment]
Looks great! If you could just add tests for this feature, I would be more than glad to merge this feature :-)

**Comment by moorereason** [comment]
@gdubicki,
If you rebase with the development branch, you will see that we've moving the wiki pages to the `docs` directory in the git repo.  So in addition to adding tests, you can also update the docs within this PR.

**Comment by gdubicki** [comment]
Docs & tests added, @moorereason @adnanh . :)

Please let me know if I need to squash too - contribution guide doesn't say what is your policy regarding that.

**Comment by adnanh** [comment]
Thank you very much for your contribution and making a webhook a much better tool for everyone!

**Pull request merged**
