### PR TITLE
Add Github Action to build & run tests

### PR DESCRIPTION
**Pull request by moorereason**

### CODE REVIEW

**Comment by moorereason** [comment]
I assumed this PR would have triggered the action.  Hmm...

**Comment by adnanh** [comment]
Maybe I have to enable something in the repo settings?

**Comment by moorereason** [comment]
I'm guessing that this PR must be committed in order to add the actions to the project.

**Comment by nvanheuverzwijn** [comment]
@adnanh You need to allow github actions to run for pull-request. I wouldn't do this because it basically allows anyone to run github actions on your repository.
You can create a branch from this PR and test the action this way.

**Comment by moorereason** [comment]
Thanks for the advice, @nvanheuverzwijn.  :+1:  So, we can merge into the `development` branch and begin testing it there.  BTW, it works great in my [`gh-action-tests`](https://github.com/moorereason/webhook/tree/gh-action-tests) branch.  See the [results](https://github.com/moorereason/webhook/actions/runs/277746096).

**Comment by nvanheuverzwijn** [comment]
@adnanh Considering github actions, would you be open to build a docker container directly form this repository and upload it to github packages ? We could also have rpm, deb, linux/mac/windows binary. All automated with github actions. @moorereason already have a very good base to start doing that.

**Comment by adnanh** [comment]
> @adnanh Considering github actions, would you be open to build a docker container directly form this repository and upload it to github packages ? We could also have rpm, deb, linux/mac/windows binary. All automated with github actions. @moorereason already have a very good base to start doing that.

Sure thing :)

**Pull request merged**
