### PR TITLE
Add support for naming env variables

### PR DESCRIPTION
**Pull request by faide**

### CODE REVIEW

**Comment by faide** [comment]
Hi, I added support for a new config variable that enables the user to name the environment variable its program will receive.

It is especially useful for source=string and for source=entire-payload schemes

```json
[
  {
    "id": "push",
    "execute-command": "bb2mm",
    "command-working-directory": "/tmp",
    "pass-environment-to-command":
    [
      {
        "source": "entire-payload",
        "envname": "PAYLOAD"
      },
      {
        "source": "string",
        "name": "PUSH"
      },
      {
        "source": "string",
        "envname": "MMURL",
        "name": "https://someurl/hooks/somehooktokengeneratedbymm"
      }
    ]
  }
]
```

will give you nice env variables:
  - **HOOK_PAYLOAD** (using the introduced feature)
  - **HOOK_MMURL** (using the introduced feature)
  - **HOOK_PUSH**

without this feature the obtained vars are:
  - **HOOK_** (it has no name and thus is not `named` :/ )
  - **HOOK_https://someurl/hooks/somehooktokengeneratedbymm** (the name is also the content and thus you won't be able to find this variable without knowing its content first, which kind of defeats the purpose)

**Comment by faide** [comment]
I fixed the tests but did not introduce new ones to cover my changes. If you are interested in this PR please let me know so I can update the test suite to add coverage for it. Cheers!

**Comment by adnanh** [comment]
:+1:

**Comment by faide** [comment]
I take this for a yes ... Let's do this then :)

I just added tests for the zone of code I modified. Added some tooling scripts to help visually understand which code is tested or not... coverage report

**Comment by faide** [comment]
If you are OK with the current state I am ready for a merge. Nothing to add to this particular PR

**Comment by adnanh** [comment]
Could you extract the `coverage` script into the [webhook-contrib](webhook-contrib) repository, since it's platform dependent and not necessary for the core webhook build, and we want to keep this repo as clean as possible :-)

Otherwise, great job :-)

**Comment by faide** [comment]
done

**Comment by adnanh** [comment]
Could you just create a PR into `development` branch, so we can merge it in, we use `master` as release branch :-)

**Comment by faide** [comment]
also done

**Pull request closed without merging**
