### PR TITLE
Warn on failed validate of empty payload signature

### PR DESCRIPTION
**Pull request by moorereason**
If signature validation fails on an empty payload, append a note to the
end of the error message.

Updates #423

### CODE REVIEW

**Comment by adnanh** [comment]
Hmm, signatures of an empty payload can still be used as a verification that the request is coming from whoever they claim to be. Maybe spitting a warning instead would be better approach?

**Comment by moorereason** [comment]
Ok.  I'll try a different approach.

**Comment by moorereason** [comment]
Force-pushed a redesign and updated title and original comment to match the commit.

**Comment by adnanh** [comment]
Awesome! Thanks :-)

**Pull request merged**
