### PR TITLE
Pass "big" binary files #162

### PR DESCRIPTION
**Pull request by col-panic**
I would appreciate feedback on the changes made. The issue itself is documented in https://github.com/adnanh/webhook/issues/162 - a usage guide is provided in https://github.com/col-panic/webhook/wiki

### CODE REVIEW

**Comment by adnanh** [comment]
This looks great!

I would just change one little thing - instead of keeping file on exit by default, I would delete it by default.

So we can rename that option to "KeepFileOnExit".

**Comment by col-panic** [comment]
While we can be sure that the file will be here on starting our hook, we can't be sure about the file still existing after the hook was run ( the script could remove the file by itself). So naming the option ```KeepFileOnExit``` would suggest that even though the file was already deleted, we will still be able to keep it. I think that this is misleading - due to this I named it ```DeleteOnExit``` ( while a more descriptive option name would be ```DeleteOnExitIfExists```). 

If you insist on your naming I can certainly go for it, but I found it more intuitive this way.

**Comment by adnanh** [comment]
Ah, you are absolutely correct. 

I would then do this cleanup by default, after the hook command is done executing, if the file is there, delete it.

Since it's a tempfile, if the user wants to keep it, they should copy it to the appropriate place in their script code, because if we don't delete it, it's gonna be deleted after machine restart anyway.

**Comment by col-panic** [comment]
Allright, I patched the code accordingly. I also updated the test file, yet I can't figure out why I still make messages like 

```
./webhook_test.go:44: not enough arguments in call to handleHook
	have (*"github.com/adnanh/webhook/hook".Hook, *map[string]interface {}, *map[string]interface {}, *map[string]interface {}, *[]byte)
	want (*"_/Users/marco/Development/goclipse-latest/git/webhook/hook".Hook, string, *map[string]interface {}, *map[string]interface {}, *map[string]interface {}, *[]byte)
./webhook_test.go:74: not enough arguments in call to handleHook
	have (*"github.com/adnanh/webhook/hook".Hook, *map[string]interface {}, *map[string]interface {}, *map[string]interface {}, *[]byte)
	want (*"_/Users/marco/Development/goclipse-latest/git/webhook/hook".Hook, string, *map[string]interface {}, *map[string]interface {}, *map[string]interface {}, *[]byte)
./webhook_test.go:98: not enough arguments in call to handleHook
	have (*"github.com/adnanh/webhook/hook".Hook, *map[string]interface {}, *map[string]interface {}, *map[string]interface {}, *[]byte)
	want (*"_/Users/marco/Development/goclipse-latest/git/webhook/hook".Hook, string, *map[string]interface {}, *map[string]interface {}, *map[string]interface {}, *[]byte)
FAIL	_/Users/marco/Development/goclipse-latest/git/webhook [build failed]
--- FAIL: TestCheckPayloadSignature256 (0.00s)
	hook_test.go:53: failed to check payload signature {"{\"a\": \"z\"}", "secret", "sha256f417af3a21bd70379b5796d5f013915e7029f62c580fb0f500f59a35a6f04c89"}:
		expected {mac:"f417af3a21bd70379b5796d5f013915e7029f62c580fb0f500f59a35a6f04c89", ok:true},
		got {mac:"f417af3a21bd70379b5796d5f013915e7029f62c580fb0f500f59a35a6f04c89", ok:false}
	hook_test.go:57: error message should not disclose expected mac: invalid payload signature sha256f417af3a21bd70379b5796d5f013915e7029f62c580fb0f500f59a35a6f04c89
FAIL
```

on make test

**Comment by adnanh** [comment]
Ahh, the #173 forgot to include request ID in the `webhook_test.go` file, I've fixed it now, pull the latest master into your branch :-)

**Comment by col-panic** [comment]
done!

**Comment by adnanh** [comment]
Can you just choose adnanh:development as base branch so I can merge it in :-)

**Comment by adnanh** [comment]
And update the wiki with the new option

**Comment by col-panic** [comment]
Ok, I changed the base, after you accepted the PR I plan to integrate the documentation from my page into your wiki in an updated version!

**Comment by col-panic** [comment]
Docu added :)

**Comment by adnanh** [comment]
Awesome, thank you very much for your contribution and making webhook a better tool!

**Pull request merged**
