### PR TITLE
Add Gitea and Uberspace Guide

### PR DESCRIPTION
**Pull request by arran-nz**
Added a guide to redeploy a static Hugo site with Webhook from a Gitea instance

### CODE REVIEW

**Comment by moorereason** [comment]
It looks like your commit is using a different email address from your Github profile.  It doesn't bother me, but pointing it out in case it was unintentional.

**Comment by arran-nz** [comment]
@moorereason Thank you! this was unintentional - Will update

**Comment by arran-nz** [comment]
Amended

**Comment by adnanh** [comment]
Fantastic guide :-) Thank you!

**Pull request merged**
