### PR TITLE
Add support for top-level JSON array in payload

### PR DESCRIPTION
**Pull request by moorereason**
Detect if leading character in JSON payload is an array bracket.  If
found, decode payload into an interface{} and then save the results into
payload["root"].  References to payload values would need to reference
the leading, "virtual" root node (i.e. "root.0.name").

### CODE REVIEW

**Comment by moorereason** [comment]
@adnanh, this is a proposed solution to #215.  Needs docs, but I wanted to get your feedback on the concept before I keep going.  Thoughts?

**Comment by adnanh** [comment]
Looks good!

**Comment by moorereason** [comment]
I've added this to the 2.8.0 milestone since I consider it an enhancement more than a bugfix.  I'll work on adding docs to this PR.

**Comment by adnanh** [comment]
This is looking great!

What do you think about adding another improvement to the webhook in this PR: when fetching the referenced parameter which turns out to be an object or an array, return a JSON string representation of it. At the moment it will invoke ToString() on the object which usually ends up with something like `map[foo: bar]` for payload such as `{"foo": "bar"}`, thoughts?

**Comment by moorereason** [comment]
@adnanh, I like the idea, but let's do that in a separate PR.  I'll make a new issue to track the change.

**Pull request merged**
