### PR TITLE
Use the github.com/ghodss/yaml library to unserialize webhooks.

### LINKED ISSUE #142: Support YAML configuration
It would be nice if this supported specifying the configuration as YAML as well as JSON to provide a slightly more human-friendly interface for casual experimentation.

### PR DESCRIPTION
**Pull request by wrouesnel**
This supports both JSON and YAML seamlessly, providing for an easier human parseable format on disk.

Closes #142.

Since this depends on external library, and I'm not sure how the project handles vendoring at the moment so I've left that as an unsolved issue just now (my personal favorite tool is govendor).

### CODE REVIEW

**Comment by adnanh** [comment]
First of all, thank you for your contribution! It is very much appreciated.

Before I can merge this PR I would need you to do a few more things:
 - [ ] add test case scenarios for loading YAML and JSON hooks definitions
 - [ ] fix mentions of `hooks json` to something along the lines of `hooks definitions`
 - [ ] create the updated pull request against the `development` branch
 - [ ] when all of the above is done, update the documentation on wiki pages to indicate that the YAML is also supported

**Comment by wrouesnel** [comment]
* Added the test scenarios.
* Updated to pull into development branch.

Not sure what you meant about updating references to `hooks json`? Other then places in the README that the filename is explicitly mentioned (not sure if you want to update those - though for "type this out" examples the YAML is nicer).

**Comment by adnanh** [comment]
I will merge this PR this week, as soon as I find some free time. I'm on a busy schedule this month. :(

**Comment by wrouesnel** [comment]
Ping! I've been building some docker containers with this version lately and its a very pleasant experience manually. Any word or needed changes for this?

**Comment by adnanh** [comment]
Expect a release with this merged this Thursday :-)

**Comment by adnanh** [comment]
Webhook 2.6.5 has been released!

https://github.com/adnanh/webhook/releases/tag/2.6.5

**Pull request merged**
