### PR TITLE
make http return code for mismatch rules configurable

### PR DESCRIPTION
**Pull request by madddi**
Hi,

we'd like to be able to easily check if a hook was successfully executed. If the hook rules were not satisfied, webhook should return a non-200 HTTP code. I think non-matching hook rules are likely a result of a "Bad Request", so this should be returned instead of 200.

### CODE REVIEW

**Comment by adnanh** [comment]
First of all, thanks for using webhook and making a PR.

I agree this would be great addition to webhook.

However, since this PR would change the default behavior of webhook other users might rely on, I would love to see this feature implemented as a per-hook configurable and global setting similar to how response headers are currently implemented. Leaving the 200 Ok to be default global setting.

If you did that, I would be more than glad to merge your contribution!

Thanks :-)

**Comment by madddi** [comment]
Good point. I'll see if I can come up with a proper solution.

**Comment by madddi** [comment]
I rebased my changes on master. The HTTP code is now configurable per hook. If not set or set to an invalid HTTP code, the default is `200 OK`.

**Comment by madddi** [comment]
I thought of this exact name as well but found it a little bit too long. But I agree that the longer name is more self-explanatory. Thanks :-)

**Pull request merged**
